; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

; [env]
; platform = ststm32
; framework = arduino
; board = giga_r1_m7
; upload_protocol = dfu
; build_flags = 
; 	-Os
; debug_build_flags = 
; 	-O0 -g
; monitor_speed = 115200

[env]
platform = renesas-ra
board = uno_r4_wifi
framework = arduino
board_build.mcu = ra4m1
board_build.f_cpu = 48000000L
monitor_speed = 115200

[env:utils]
build_src_filter = 
	+<**>
	-<space_robot.cpp>
	-<utils/**.cpp>
	+<utils/motoron_set_addr.cpp>
lib_deps = 
	kkloesener/MFRC522_I2C@^1.0
	pololu/Motoron@^1.5.0

[env:release]
build_src_filter = 
	+<**>
	-<utils/*.cpp>
lib_deps = 
	kkloesener/MFRC522_I2C@^1.0
	pololu/Motoron@^1.5.0

[platformio]
include_dir = src/include
src_dir = src
lib_dir = libraries
