#pragma once

#include "tinyfsm.hpp"
#include <cstdint>

// ============================================================
// Auto-generated from docs/robot_fsm.puml
// Do NOT edit this file manually; re-run tools/generate_fsm.py
// ============================================================

struct RobotEvent : tinyfsm::Event {
    enum class Type {
        AirlockA_Reached,
        AllSeedsPlanted,
        AssistanceComplete,
        BatteryDepleted,
        BonusTrigger,
        ChargeComplete,
        DoorOpened,
        EmergencyTimerExpired,
        EmergencyWarning,
        ExitClearanceGranted,
        Launch,
        LightRecorded,
        LineDetected,
        LineLost,
        LowBattery,
        MissionComplete,
        ObstacleCleared,
        ObstacleDetected,
        OpenDoorRequest,
        ParkingReached,
        PeriodicLightScan,
        RFIDDetected,
        RFID_B_Read,
        ReadSuccess,
        Response_Covered,
        Response_Fertile,
        Response_Infertile,
        ReviveButtonPressed_LED_RedToGreen,
        SeedPlanted,
        TagA_Pressed,
        TagA_Reached,
        TimerExpired,
        TunnelExited,
        WiFiReenabled,
    } type;

    uint32_t uid = 0;
    bool was_charging = false;
};

struct FSM_Robot : tinyfsm::Fsm<FSM_Robot> {
    // History emulation for Navigating sub-states
    enum class NavMode { LineFollowing, GridTraversing };
    NavMode previous_nav_mode_ = NavMode::LineFollowing;

    virtual void react(RobotEvent const & e) = 0;
    virtual void entry() = 0;
    virtual void exit() = 0;
};

struct State_AssistingEntry_MovingToTagA : FSM_Robot {
    void entry() override;
    void exit() override;
    void react(RobotEvent const & e) override;
};

struct State_AssistingEntry_PressingTagA : FSM_Robot {
    void entry() override;
    void exit() override;
    void react(RobotEvent const & e) override;
};

struct State_AssistingEntry_ReturningToParking : FSM_Robot {
    void entry() override;
    void exit() override;
    void react(RobotEvent const & e) override;
};

struct State_BeingRevived : FSM_Robot {
    void entry() override;
    void exit() override;
    void react(RobotEvent const & e) override;
};

struct State_Charging : FSM_Robot {
    void entry() override;
    void exit() override;
    void react(RobotEvent const & e) override;
};

struct State_EmergencyReturn : FSM_Robot {
    void entry() override;
    void exit() override;
    void react(RobotEvent const & e) override;
};

struct State_EnteringBase_TraversingTunnelA : FSM_Robot {
    void entry() override;
    void exit() override;
    void react(RobotEvent const & e) override;
};

struct State_EnteringBase_WaitingForDoor : FSM_Robot {
    void entry() override;
    void exit() override;
    void react(RobotEvent const & e) override;
};

struct State_ExitingBase_ApproachingTagB : FSM_Robot {
    void entry() override;
    void exit() override;
    void react(RobotEvent const & e) override;
};

struct State_ExitingBase_RequestingClearance : FSM_Robot {
    void entry() override;
    void exit() override;
    void react(RobotEvent const & e) override;
};

struct State_ExitingBase_TraversingTunnelB : FSM_Robot {
    void entry() override;
    void exit() override;
    void react(RobotEvent const & e) override;
};

struct State_ExitingBase_WaitingForDoorB : FSM_Robot {
    void entry() override;
    void exit() override;
    void react(RobotEvent const & e) override;
};

struct State_ReturningToBase : FSM_Robot {
    void entry() override;
    void exit() override;
    void react(RobotEvent const & e) override;
};

struct State_Standby : FSM_Robot {
    void entry() override;
    void exit() override;
    void react(RobotEvent const & e) override;
};

struct State_Stranded : FSM_Robot {
    void entry() override;
    void exit() override;
    void react(RobotEvent const & e) override;
};

struct State_SurfaceExploration_Navigating_GridTraversing : FSM_Robot {
    void entry() override;
    void exit() override;
    void react(RobotEvent const & e) override;
};

struct State_SurfaceExploration_Navigating_LineFollowing : FSM_Robot {
    void entry() override;
    void exit() override;
    void react(RobotEvent const & e) override;
};

struct State_SurfaceExploration_Navigating_ObstacleAvoidance : FSM_Robot {
    void entry() override;
    void exit() override;
    void react(RobotEvent const & e) override;
};

struct State_SurfaceExploration_Planting : FSM_Robot {
    void entry() override;
    void exit() override;
    void react(RobotEvent const & e) override;
};

struct State_SurfaceExploration_QueryingServer : FSM_Robot {
    void entry() override;
    void exit() override;
    void react(RobotEvent const & e) override;
};

struct State_SurfaceExploration_ReadingRFID : FSM_Robot {
    void entry() override;
    void exit() override;
    void react(RobotEvent const & e) override;
};

struct State_SurfaceExploration_ScanningForLight : FSM_Robot {
    void entry() override;
    void exit() override;
    void react(RobotEvent const & e) override;
};
